# Generated by Django 4.2.16 on 2024-09-24 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_goal_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='determination',
        ),
        migrations.AddField(
            model_name='goal',
            name='priority',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
