# Generated by Django 4.2.16 on 2024-09-24 14:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_goal_determination_goal_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='priority',
        ),
        migrations.AddField(
            model_name='goal',
            name='days',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
